name: Build

on:
  push:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '**.md'
      - '.github/workflows/update-date.yml'
      - '.github/workflows/winget-publish.yml'
  pull_request:
    branches: ["main"]
    paths-ignore:
      - 'docs/**'
      - '**.md'

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup sccache
        uses: mozilla/sccache-action@v0.0.5
        env:
          SCCACHE_GHA_ENABLED: "true"

      - name: Setup MSVC
        uses: ilammy/msvc-dev-cmd@v1

      - name: Configure CMake
        env:
          SCCACHE_GHA_ENABLED: "true"
        run: cmake -B build -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }}

      - name: Build
        env:
          SCCACHE_GHA_ENABLED: "true"
        run: cmake --build build --config ${{ env.BUILD_TYPE }}

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: QuickImageViewer
          path: build/Release/QuickImageViewer.exe
          if-no-files-found: error
