name: Publish to WinGet

on:
  release:
    types: [released]
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to WinGet
        uses: vedantmgoyal9/winget-releaser@v2
        with:
          identifier: icyhoty2k.QuickImageViewer
          token: ${{ secrets.WINGET_TOKEN }}
          # Uncomment if you publish multiple assets and want only the .exe picked up:
          # installers-regex: '\.exe$'
